name: Codecov

on:
  pull_request:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"
      - "main"

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          ini-values: assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On
          extensions: pdo, pdo_mysql, swoole
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: composer update --no-interaction --no-progress --ansi

      - name: Run PHPUnit to collect coverage
        run: composer phpunit:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
