name: PHP CS Fix analysis

on:
  pull_request:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"
      - "main"

jobs:
  cs-fix:
    name: PHP CS Fix on PHP 8.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2, php-cs-fixer:3.58
          extensions: pdo, pdo_mysql, swoole

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: composer update --no-interaction --no-progress --ansi

      - name: Run PHP CS Fix
        run: php-cs-fixer check