name: Tests

on:
  pull_request:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"
      - "main"

jobs:
  phpunit:
    name: PHPUnit on PHP${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.2' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On
          tools: composer:v2
          extensions: pdo, pdo_mysql, swoole

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: composer update --no-interaction --no-progress --ansi

      - name: Execute PHPUnit
        run: composer phpunit
